### ISSUE TITLE
variable token has expired

### ISSUE THREAD

**Issue by francima961** [AdminAnticaptcha/anticaptcha-nodejs#5]
I use the GeeTestTaskProxyless using Antocpatcha.js class with puppeteer. 

While retreiving the solution I get the following error: 

`Captcha provider reported that additional variable token has expired.`

The support desk says it is because the tokens may have expired and that I should get a new pair of tokens, however : 

1.  The token didn't change and the captcha remain solvable on the given page
2. On Anti-Captcha platform, I can see the captcha being solved and validated + I'm being charged for it / so it seems tokens are just fine ... 

@AdminAnticaptcha / @Armalon  how may I deal with this ? 

P.S : Here is my full stacktrace from the moment I receveive my task id
`
84024488`
`Waiting 5 seconds`
`Waiting 2 seconds`
`Waiting 2 seconds`
`Waiting 2 seconds`
`Waiting 2 seconds`
`Waiting 2 seconds`
`Waiting 2 seconds`
`Waiting 2 seconds`
`null`
`Error: Captcha provider reported that additional variable token has expired.`

Cheers

**Comment by nquoctuan** [comment]
hi, any update? I got same issue

**Comment by AdminAnticaptcha** [comment]
1. This issue is not related to NodeJS code at all.
2. Anti-Captcha API transmits this error from Geetest servers. You may address your question to Geetest developers.
3. Suggestion that you are charged for these errors if false.
