### ISSUE TITLE
Using promises instead of callbacks?

### ISSUE THREAD

**Issue by gabriel-ramirez-q2** [AdminAnticaptcha/anticaptcha-nodejs#7]
let me know if it's on your radar or you would accept a PR?

**Comment by HarrisonHenri** [comment]
Dear @AdminAnticaptcha , thank you for this great module!

I am a developer and would like to know if can we use async/await syntax already?

Thanks in advance!

**Comment by AdminAnticaptcha** [comment]
No idea. If you're a developer, you tell me!

**Comment by HarrisonHenri** [comment]
Thank you anyway!

**Comment by BitesizedLion** [comment]
Would be very nice if someone decided to do this (Even anti-captcha themselves possibly?)

**Comment by AdminAnticaptcha** [comment]
Please switch to our npm package.

https://github.com/AdminAnticaptcha/anticaptcha-npm
https://www.npmjs.com/package/@antiadmin/anticaptchaofficial
